name: "Build and push OCI image"
on:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - uses: cachix/cachix-action@v14
      with:
        name: mindwm
        # If you chose API tokens for write access OR if you have a private cache
        # we're not pushing anything to the cachix
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: build OCI image
      run: nix --accept-flake-config build .#docker
    - name: Set up skopeo environment
      uses: warjiang/setup-skopeo@v0.1.3
    - name: Login to repository
      run: |
        echo ${{ secrets.REGISTRY_TOKEN }} | skopeo login -u metacoma --password-stdin ghcr.io
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ vars.DEST_REGISTRY }}/${{ github.event.repository.name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
        flavor:
          latest=false
    - name: get image name
      run: echo "TAGS=${{ steps.meta.outputs.tags }}"

    - name: Push image
      run: |
        skopeo --version
        skopeo copy \
        docker-archive:./result \
        docker://${{ steps.meta.outputs.tags }}
